### ISSUE TITLE
Request: Support PF2e

### ISSUE THREAD

**Issue by jocolamarco** [manuelVo/foundryvtt-award-xp#12]

**Comment by manuelVo** [comment]
To add compatiblility for PF2 I need the following information about the game system:
- The attribute in whch the current xp is stored for an actor
- The attribute which stores the amount of xp that need to be reached for the next levelup (alternatively a formula to calculate that amount)
- If PF2 has any concept of a challenge rate (or something similar) like dnd5e and pathfinder 1 do I need the name of that concenpt and the conversion table from challange rate to matching xp.

**Comment by jocolamarco** [comment]
> The attribute in whch the current xp is stored for an actor

**actor.data.data.details.xp.value**

> The attribute which stores the amount of xp that need to be reached for the next levelup (alternatively a formula to calculate that amount)

**actor.data.data.details.xp.max**

> If PF2 has any concept of a challenge rate (or something similar) like dnd5e and pathfinder 1 do I need the name of that concenpt and the conversion table from challange rate to matching xp.

**Slightly different from 5e as it depends on the Party Level:**
[https://2e.aonprd.com/Rules.aspx?ID=575](url)

**Comment by manuelVo** [comment]
PF2's Party Level table doesn't quite fit into how Award XP handles CR. I've decided to disable that feature in PF2. Otherwise, PF2 is now supported.
