### ISSUE TITLE
[Request] Don't split XP for Splittermond

### ISSUE THREAD

**Issue by gsterling** [manuelVo/foundryvtt-award-xp#15]
Splittermond doesn't split XP. All players get the same after each adventure. Normally 10, 15 or 20. So it's not fixed.

But I have to multiply this by number of players. Could you add the option (or even default for Splittermond) to give the XP to each player?

Could you also maybe filter the list to only show actors, that are linked to a player?

Thank you!

**Comment by manuelVo** [comment]
For the second request, you can select which actors are being shown in Award XP's module configuration.

**Comment by gsterling** [comment]
> For the second request, you can select which actors are being shown in Award XP's module configuration.

Thanks, I don't know why I didn't check it.

**Comment by jhubsharp** [comment]
This would be useful for PF2e as well.
