### ISSUE TITLE
V11 Update Request

### ISSUE THREAD

**Issue by GorgoPrimus** [manuelVo/foundryvtt-award-xp#19]
I absolutely adore this little module, so it'd be really great if it got updated for V11. Thanks!

**Comment by manuelVo** [comment]
The module seems to be working fine in v11 in my testing. Please describe the issues you're encountering with this module, so I can have at look what might be causing them.

**Comment by GorgoPrimus** [comment]
It works but gives a giant warning that it’s out of date and that it uses some depreciated script. I’ll try to get a more detailed account later today.

**Comment by GorgoPrimus** [comment]
`The module "award-xp" is using "name" which is deprecated in favor of "id"
The module "award-xp" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object`
on the main menu and
`foundry.js:67697 Award XP is unmaintained and may introduce stability issues to your game.
fetch @ foundry.js:67697
pf2e.mjs:367 Award XP is unmaintained and may introduce stability issues to your game.
(anonymous) @ pf2e.mjs:367
`upon start-up.

It's also throwing up the start-up error on my main server, and that one is still on v10.

**Comment by manuelVo** [comment]
A version with updated manifest has just been released.

**Comment by GorgoPrimus** [comment]
That worked for V10, but upon upgrading my server to V11 I can see this under my installed modules: 
![Untitled](https://github.com/manuelVo/foundryvtt-award-xp/assets/126842722/4b95c3ec-6f92-4ba4-a1cc-3c8cae1abb54)
I don't get any errors or alerts in the game, but thought it worth bringing up to you in case it causes problems later.

Thanks!
