### ISSUE TITLE
Foundry V12; D&D v3.2.1 Support

### ISSUE THREAD

**Issue by Zalakoth** [manuelVo/foundryvtt-award-xp#23]
As of D&D 5E v3.2.1 (Foundry V12) the "Award XP Button" from the module does not function. I absolutely love this module, and want to continue using it. There are no others like if for the 5E system.

**Comment by GorgoPrimus** [comment]
Also not working in Pathfinder 2E when it did for over a year before now. It just doesn't work. :(

**Comment by Dominemesis** [comment]
Seconding GorgoPrimus, Award XP isn't working in PF2E since Foundry V12 Build 328 update anymore.  Pressing the button does nothing, no menu, no error, no prompts, nothing.

**Comment by ap3h3ad** [comment]
I would also like seeing a support for Splittermond v. 12.0. :)

**Comment by Zalakoth** [comment]
Going to close this as resolved, since I recently learned 5th Edition D&D has a built-in system for Awarding XP now. Good luck to the rest of you.
